// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DSS.Data.Model.Migrations
{
    public sealed partial class InitialDatabaseCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialDatabaseCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201209151244025_InitialDatabaseCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
