// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DSS.Data.Model.Migrations
{
    public sealed partial class ConfigureManyToManyKeywordsCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfigureManyToManyKeywordsCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201209231030436_ConfigureManyToManyKeywordsCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
