// <auto-generated />
namespace DSS.Data.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MakeLogFKsNonNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeLogFKsNonNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201304010034069_MakeLogFKsNonNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
