// <auto-generated />
namespace DSS.Data.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DocumentDescriptionAndFKChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DocumentDescriptionAndFKChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201303312232092_DocumentDescriptionAndFKChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
