// <auto-generated />
namespace DSS.Data.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateRelationBetweenUsersAndDocs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateRelationBetweenUsersAndDocs));
        
        string IMigrationMetadata.Id
        {
            get { return "201302161751054_CreateRelationBetweenUsersAndDocs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
